[build]
builder = "nixpacks"
buildCommand = "cd mongodb && npm install"
nixpacksConfigPath = "mongodb/nixpacks.toml"

[deploy]
startCommand = "cd mongodb && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[service]
name = "ai-task-api"

[env]
MONGODB_URI = "mongodb+srv://mrkrog:Krog1234@cluster0.iqxvxvz.mongodb.net/ai-task-api?retryWrites=true&w=majority" 