[build]
builder = "nixpacks"
buildCommand = "cd mongodb && npm install"

[deploy]
startCommand = "cd mongodb && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[service]
name = "ai-task-api" 